# Handling Data for Nepali Post Sentiment Analysis

Following datasets will be used for sentiment analysis of emotions in different posts online. 
- https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv
- https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv
- https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv

This dataset is choosen to let model understand different emotion via texts. This will allow us to get information on emotion or sentiment of human writing a post. Also the data from reddit where Nepali people posts will be collected and categorized and analysed using KMeans then again feed to the senitment analysis to get overall picture of nepali people's discussion and their emotions regarding it.

## Download GoEmotions dataset

### import libraries 
- request
- pandas

In [1]:
import requests
import pandas as pd 
import os

In [2]:
go_emotion_base_url = "https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/"

# go emotion datasets names
go_emotion_datasets_names = [
    "goemotions_1.csv",
    "goemotions_2.csv",
    "goemotions_3.csv"
]

# make an empty list to append loaded pd
go_emotions_list = []

# use loop for goemotion
for goemotion in go_emotion_datasets_names:
    df = pd.read_csv(f"{go_emotion_base_url}{goemotion}")
    go_emotions_list.append(df)
    print(f"{goemotion} Loaded!")
    
go_emotions_dataset = pd.concat(go_emotions_list, ignore_index=True)

print(f"SHAPE OF FINAL GO_EMOTION DATASET = {go_emotions_dataset.shape}")
go_emotions_dataset.head(3)

goemotions_1.csv Loaded!
goemotions_2.csv Loaded!
goemotions_3.csv Loaded!
SHAPE OF FINAL GO_EMOTION DATASET = (211225, 37)

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,eew5j0j,Brdd9,nrl,t3_ajis4z,t1_eew18eq,1.548381e+09,1,False,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,eemcysk,TheGreen888,unpopularopinion,t3_ai4q37,t3_ai4q37,1.548084e+09,37,True,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",ed2mah1,Labalool,confessions,t3_abru74,t1_ed2m7g7,1.546428e+09,37,False,0,...,0,0,0,0,0,0,0,0,0,1

## Clean GoEmotions Data as per Needed:
- remove id, author, subreddit, link_id, parent_id, created_utc and rater_id, example_very_unclear
- clean text column (text preprocessing)

In [3]:
# drop unnecessary columns
go_emotions_dataset.drop(columns=[
    "id", "author", "subreddit", "link_id", 
    "parent_id", "created_utc", "rater_id", 
    "example_very_unclear"
], inplace=True)

print("Dropped unnecessary columns in place!")

Dropped unnecessary columns in place!

### Clean text requires additional libraries:
- regex
- bs4 BeautifulSoup
- string

Create a function to clean text usable in future as well. This function will remove html, punctuations, urls, additonal spaces, emojis, and also lowercase the text. It is required as a basic pre-processing for TF-IDF NLP.

In [4]:
import re
from bs4 import BeautifulSoup
import emoji

REMOVE_PHRASES = [
    "nice video",
    "great video",
    "awesome video",
    "amazing video",
    "excellent video",
    "good video",
    "best video",
    "nice content",
    "great content",
    "awesome content",
    "good content",
    "keep it up",
    "good job",
    "great job",
    "awesome job",
    "well done",
    "thanks for sharing",
    "thank you for sharing",
    "thanks for the video",
    "thank you for the video",
    "thanks for uploading",
    "more videos please",
    "upload more",
    "keep uploading",
    "keep making videos",
    "first comment",
    "early gang",
    "still watching",
    "watching in 2026",
    "who is watching in 2026",
    "anyone here in 2026"
]

REMOVE_WORDS = {
    "thanks",
    "thank",
    "video",
    "videos",
    "content",
    "podcast",
    "bro",
    "sir",
    "nice",
    "great",
    "awesome",
    "amazing",
    "good",
    "best",
    "wow",
    "pls",
    "please"
}


def clean_text(text):

    if not isinstance(text, str):
        return ""

    # Remove HTML
    text = BeautifulSoup(text, "html.parser").get_text()

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Remove emojis
    text = emoji.replace_emoji(text, "")

    # Remove punctuation (keep English + Devanagari)
    text = re.sub(r"[^\w\s\u0900-\u097F]", " ", text)

    # Remove common useless phrases
    for phrase in REMOVE_PHRASES:
        text = text.replace(phrase, " ")

    # Remove common useless words
    words = [
        word for word in text.split()
        if word not in REMOVE_WORDS
    ]

    # Remove extra spaces
    text = " ".join(words)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [5]:
# Apply the function to text column
go_emotions_dataset["text"] = go_emotions_dataset["text"].apply(clean_text)

# See few texts how  they look
go_emotions_dataset.head()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,that game hurt,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,sexuality shouldn t be a grouping category it ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,you do right if you don t care then fuck em,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,man i love reddit,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,name was nowhere near them he was by the falcon,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

### Drop null values if any and Save

In [6]:
# Drop na value and save
go_emotions_dataset = (
    go_emotions_dataset
    .dropna(subset=["text"])
)
# Drop empty string
go_emotions_dataset = go_emotions_dataset[
    go_emotions_dataset["text"].str.strip() != ""
].reset_index(drop=True)

In [7]:
go_emotions_dataset = go_emotions_dataset.sample(frac=1, random_state=41)

# Save to the datasets folder
go_emotions_dataset.to_csv("./datasets/go_emotions.csv", index=False)

## Download YT Comments
This data will be downloaded googles Youtube API key. This dataset will contain nepali's voice including youths. The comments represent what nepali people think on current government, system, justice, education, etc. This shows if citizens are happy or not in different aspects of the country.

### Import Libraries
- build from googleapiclient.discovery
- dotenv
- LangDetectException

In [8]:
from dotenv import load_dotenv
from googleapiclient.discovery import build

# config dotenv
load_dotenv("./.env")

True

In [9]:
# youtube api key access
youtube = build(
    "youtube",
    "v3",
    developerKey=os.getenv("YT_API_KEY")
)

### Extracts channel ID
The channel id is not usually present like it used to, so it is necessary to extract the channel's id before extracting contents from the Api.

In [10]:
def get_channel_id(channel):

    # Already a channel ID
    if channel.startswith("UC"):
        return channel


    # Handle (@name)
    if channel.startswith("@"):

        response = youtube.channels().list(
            part="id",
            forHandle=channel.replace("@","")
        ).execute()


        if not response.get("items"):
            raise Exception(
                f"Channel not found: {channel}"
            )

        return response["items"][0]["id"]

    raise Exception(
        f"Invalid channel format: {channel}"
    )

### Selection of Channels
Only few channels are selected:
- TechTanka
- WhySoOffend
- Thaharesearch
- eon_visuals
- TheNepaliComment

These channels are popular in the youtube explaining current problems and news of Nepal. They also talk about: politics, corruption, system, justice, etc which brings engaging viewrs on the video who comment and share their point of view.

In [11]:
channels = [
    # News
    get_channel_id("@RoutineofNepalBanda"),
    get_channel_id("@SidhaKura_"),
    get_channel_id("@insidenepalnews"),
    get_channel_id("@samacharpati"),

    # Politics
    get_channel_id("@WhySoOffended"),
    get_channel_id("@TheNepaliComment"),
    get_channel_id("@MisguidedNepal"),
    get_channel_id("@inside-kura"),

    # Podcasts
    get_channel_id("@Sushant_Pradhan"),
    get_channel_id("@hernekatha"),

    # Research
    get_channel_id("@Thaharesearch"),
    get_channel_id("@IdeapreneurNepal"),

    # Tech
    get_channel_id("@TechTanka"),
    get_channel_id("@GadgetByteNepali"),
    get_channel_id("@PratimaAdhikariTech"),

    # Economy
    get_channel_id("@merolaganiofficial"),
    get_channel_id("@shareSansar2641"),

    # Entertainment
    get_channel_id("@OSRDigital"),
    get_channel_id("@budhasubbamusic"),
    get_channel_id("@highlightsnepal2009"),

    # Sports
    get_channel_id("@HamroKhelkud"),

    # Documentary
    get_channel_id("@eon_visuals"),
    get_channel_id("@WhatsWith."),

    # Youth
    get_channel_id("@SwagatGyawali1"),
    get_channel_id("@NepalShowofficial"),

    # General
    get_channel_id("@BishwoGhatana9")
]

### Extract playlists and recent videos

In [12]:
def get_upload_playlist(channel_id):

    response = youtube.channels().list(
        part="contentDetails",
        id=channel_id
    ).execute()
    return response["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]

In [13]:
def get_recent_videos(
    channel_id,
    start_date,
    end_date,
    limit=10
):
    response = youtube.search().list(
        part="snippet",
        channelId=channel_id,
        order="date",
        maxResults=limit,
        type="video",
        publishedAfter=start_date,
        publishedBefore=end_date
    ).execute()

    videos=[]

    for item in response.get("items", []):

        videos.append({
            "video_id": item["id"]["videoId"],
            "title": item["snippet"]["title"],
            "date": item["snippet"]["publishedAt"]
        })

    return videos

### Recieve Comments
This function is the main function used internally to fetch all the comments in the video.

In [14]:
def get_comments(video_id, limit=500):

    comments=[]
    
    request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        maxResults=100,
        textFormat="plainText"
    )

    while request and len(comments) < limit:
        try:
            response = request.execute()
        except:
            break

        for item in response["items"]:
            snippet = (
                item["snippet"]
                ["topLevelComment"]
                ["snippet"]
            )

            comments.append({
                "comment": snippet["textDisplay"],
                "published_at": snippet["publishedAt"]
            })

        token = response.get("nextPageToken")

        if token:
            request = youtube.commentThreads().list(
                part="snippet",
                videoId=video_id,
                pageToken=token,
                maxResults=100,
                textFormat="plainText"
            )
        else:
            break
        
    return comments

### Quality control of Comments
This function only passes the quality comments. The quality control must fullfill following criteria for passing:
- Language must be English (NO-Devnagari)
- Length of raw text must be above 5
- Remove low value adding phrases

No-devnagari because devnagari will add additional challange to preprocess, meaning extraction and also creates larger groups for model's embedding to understand. Also there are limitations on semantic datasets for devnagari (NEPALI). This will also affect K-Means Clustering as the model might just seperate Devnagari embedding to a seperate chunk not giving approprite meaning with english embeddings.

Length of text must be above 5 because raw text too short might give lower semantic value. This does not give detail emotion on how person relates and feels, a simple " I have done this ..... and ..... which caused me to be depressed." structured is needed instead of "I am very sad." For model to generalize well.

Removal of useless phrases simply means removing comments that contains low value adding texts such has : nice video, wow, upload more, etc. as this does not align with the project's problem and rather focus on what people are talking about video not problem.

In [15]:
def is_quality_comment(text):
    if len(text.split()) < 10:
        return False

    low=text.lower().strip()

    useless = [
    "best podcast",
    "best video",
    "video",
    "nice video",
    "great video",
    "awesome video",
    "amazing video",
    "excellent video",
    "good video",
    "very good video",
    "best video",
    "cool video",
    "beautiful video",
    "wonderful video",
    "fantastic video",
    "brilliant video",
    "incredible video",
    "interesting video",
    "nice content",
    "great content",
    "awesome content",
    "amazing content",
    "good content",
    "best content",
    "love this content",
    "loved this content",
    "keep it up",
    "thanks for the video",
    "thank you for the video",
    "thanks for uploading",
    "thanks for sharing",
    "thank you for sharing",
    "thanks for making this",
    "appreciate the video",
    "appreciate this video",
    "nice one",
    "good one",
    "great one",
    "awesome one",
    "well done",
    "good job",
    "great job",
    "awesome job",
    "first",
    "first comment",
    "early",
    "early gang",
    "who is watching in 2026",
    "anyone here in 2026",
    "still watching",
    "watching in 2026",
    "make more videos",
    "good morning",
    "good afternoon",
    "goog night",
    "more videos please",
    "upload more",
    "keep uploading",
    "keep making videos",
    "keep it up",
    "thanks",
    "thank you"
]

    for phrase in useless:
        if phrase in low:
            return False

    return True

### The main Scrape Function
Extracts video -> Extracts Comment -> Checks Quality -> Use/Throw

In [16]:
def scrape_channels(channels, start_date, end_date, limit):

    data=[]

    for channel_id in channels:
        print("CHANNEL:", channel_id)
        videos=get_recent_videos(
            channel_id,
            start_date,
            end_date,
            limit
        )
        
        for video in videos:
            print(
                "VIDEO:",
                video["title"]
            )
            comments=get_comments(
                video["video_id"]
            )
            for comment in comments:
                if is_quality_comment(comment["comment"]):
                    data.append({
                        "channel":channel_id,
                        "video":video["title"],
                        "video_id":video["video_id"],
                        "comment":comment["comment"],
                        "published_at":comment["published_at"]
                    })

    return pd.DataFrame(data)

In [17]:
yt_comments = scrape_channels(channels, "2024-01-01T00:00:00Z", "2026-07-25T00:00:00Z", 10)
yt_comments.head()

CHANNEL: UC2rariKhGBaLf0qmhWQv3KQ
VIDEO: Nepal&#39;s First Modern Tunnel? l  RONB Explained
VIDEO: Is kichkandi Real ? l Highway ko Kichkandi l RONB Explained  #ronb
VIDEO: Is kichkandi Real ? l Highway ko Kichkandi l RONB Explained
VIDEO: Fast Track or Slow Track? | RONB Explained
VIDEO: FINAL MATCH (MANTAIN FC _CURUCAO vs INSIGHT VISION_ BRAZIL)  RONB FUTSAL 2026
VIDEO: RONB Futsal 2026 | Live 🔴 | Day 5 | FINAL DAY
VIDEO: 3rd PLACE ENGLAND (HIMALAYA FC) V JORDAN (KORIBATI FC) RONB FUTSAL 2026
VIDEO: SEMI FINAL 2- BRAZIL (INSIGHT VISION) V JORDAN (KORIBATI FC) RONB FUTSAL 2026
VIDEO: RONB Futsal 2026 | Live 🔴| Day 4
VIDEO: RONB Futsal 2026 | Live 🔴| Day 4
CHANNEL: UC8CTPZVjEowxUO4dqRpyksA
VIDEO: गृहमन्त्री सुधन गुरुङ LIVE, संघीयता सबलीकरण तथा राष्ट्रिय सरोकार समितिको बैठक
VIDEO: नेपालमै पहिलो पटक गाँजा खेतिलाई वैधानिकता  || Cannabis legalized in Nepal !  || SIDHAKURA ||
VIDEO: काँग्रेसको जरा अभियानको समापन र नयाँ अभियानको घोषणा LIVE
VIDEO: काँग्रेसको जरा अभियानको समापन र नयाँ अभियानको घोषणा LIVE
VIDEO: कहिले बन्ला चक्रपथ ? विस्तार कार्यमा किन भइरहेछ ढिलाइ ?The Ring Road Expansion Dilemma | SIDHAKURA |
VIDEO: पछिल्लो परिस्थिति जलन अस्पतालमा छैन खाली बेड || SIDHAKURA ||
VIDEO: बसपार्क घटनाको नालिबेली || SIDHAKURA ||
VIDEO: २५ जना मानिसको ज्यान लिएको ध्रुवे हात्ति || DHURBE HATTI || THE REPORTER || SIDHAKURA ||
VIDEO: कांग्रेस इतर पक्षको कार्यक्रम LIVE
VIDEO: THE SUKUNA FILES: एकै स्कुलका आधा दर्जन शिक्षकबाट छात्रामाथि भएका हर्कत || SIDHAKURA ||
CHANNEL: UC3v3VpUyf34SLfN1IyUlMeA
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
VIDEO: News🔴today nepali news aaj ka mukhya samachar taja
CHANNEL: UC09hwXZEtHcScFWebDsj7cA
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 9 gate 2083
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 8 gate 2083.
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 8 gate 2083
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 7 gate 2083.
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 7 gate 2083
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 6 gate 2083.
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 6 gate 2083
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 5 gate 2083.
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 5 gate 2083
VIDEO: Today news 🔴 nepali news | aaja ka mukhya samachar, nepali samachar live | Saun 4 gate 2083.
CHANNEL: UC2CAM55AnDflrpC20uH700A
VIDEO: SKILLS are the NEW DEGREE! | WSO | Binayak Kuikel
VIDEO: Nepali OTT&#39;s Biggest Bet Ever | WSO | Binayak Kuikel
VIDEO: What If 100 INR = 100 NPR? | WSO | Binayak Kuikel
VIDEO: Balen&#39;s Blunder or Strategic Move? | WSO | Binayak Kuikel
VIDEO: Karki Aayog Vs. Human Rights Commission Report | WSO | Binayak Kuikel
VIDEO: The Quietest Prime Minister EVER!! | WSO | Binayak Kuikel
VIDEO: NOC: ALWAYS ON LOSS!! Here’s Why | WSO | Binayak Kuikel
VIDEO: Balen Government After 30 DAYS | WSO | Binayak Kuikel
VIDEO: Why are they Fighting for JUSTICE? | WSO | Binayak Kuikel
VIDEO: The man who Secretly CONTROLLED Nepal | WSO | Binayak Kuikel
CHANNEL: UCIUpvBA9ibPWHaDeH0G49Aw
VIDEO: Is Ronaldo still THE GOAT without the World Cup?
VIDEO: The Prince who could never become King :(
VIDEO: What it takes for Nepal to host the World Cup?
VIDEO: The real reason behind Cape Verde’s incredible run!
VIDEO: This Could be Nepal’s WORST DISASTER
VIDEO: The most CONTROVERSIAL goal in football history!                            #worldcup
VIDEO: We tested Kathmandu’s drinking water and found what companies don’t tell you
VIDEO: The Day Nepal Hosted the FIFA World Cup
VIDEO: Balen&#39;s Statement on Border: Right or Wrong?
VIDEO: The Problem with Balen&#39;s Politics
CHANNEL: UCBgaV1AaT5h9dy_XHbZhhKA
VIDEO: WHAT IF 1 Indian Rupees = 1 Nepali Rupees? || Misguided Nepal
VIDEO: BALEN SHAH Made a HUGE Mistake? || Nepal-India Border Dispute
VIDEO: WHO is the RICHEST MINISTER of Balen&#39;s Cabinet?
VIDEO: Can BALEN save the DYING FEWA LAKE? | Misguided Nepal
VIDEO: 48 HOURS of PM BALEN: Justice or REVENGE? | Misguided Nepal
VIDEO: Who are BALEN’S 14 Powerful MINISTERS?
VIDEO: KP OLI ARRESTED !! Inside Sudan Gurung&#39;s Midnight Masterstroke
VIDEO: How much is the SALARY of a Samsaad? Member of Parliament
VIDEO: The MOST POWERFUL Politicans who LOST BADLY
VIDEO: The UNSATISFYING LOSS of KULMAN GHISING || कुलमानको पतन ?
CHANNEL: UCF1v7EK696qrs10uMfa9O-Q
VIDEO: नेपालको Railway Failure: 100 वर्षको अधुरो सपना
VIDEO: Prince Dipendra: Hero, Villain, or Victim?
VIDEO: Lionel Messi को Untold Story | गरीब केटादेखि Football GOAT सम्म
VIDEO: Balen Shah&#39;s First 100 Days Explained
VIDEO: 2035 सम्म नेपाल कहाँ पुग्छ? (Data Says This)
VIDEO: Cristiano Ronaldo Biography: गरिबीदेखि GOAT बन्नेसम्मको अकल्पनीय यात्रा
VIDEO: नेपाल–भारत सम्बन्धको त्यो इतिहास, जुन धेरैलाई थाहा छैन!
VIDEO: Just Another Budget? | Nepal Budget 2083/2084 Analysis
VIDEO: Is Democracy Failing in Nepal? | Mahendra vs Balen
VIDEO: रास्वपाको उदयपछि कांग्रेस, एमाले, माओवादी — के गर्दैछन्?
CHANNEL: UCa6Sl0jhPyEgkWVU43pVDgg
VIDEO: How Surgeons Create a Natural Hairline | Dr Smriti Shrestha | Sushant Pradhan Podcast
VIDEO: The Royal Massacre No One Talks About | Sagar Dhakal | Sushant Pradhan Podcast
VIDEO: Why Calling Yourself &#39;Communist&#39; in Nepal is Embarrassing | Sagar Dhakal | Sushant Pradhan Podcast
VIDEO: The Mother-Child Theory of Leadership | Sagar Dhakal | Sushant Pradhan Podcast
VIDEO: Nepal’s Biggest Trap | Sagar Dhakal | Sushant Pradhan Podcast
VIDEO: How Empires Fall (And What Nepal Must Learn) | Sagar Dhakal | Sushant Pradhan Podcast
VIDEO: Can Too Many Skincare Products Damage Your Skin? | Dr Smriti Shrestha | Sushant Pradhan Podcast
VIDEO: Are Steroid Creams Damaging Your Skin? | Dr Smriti Shrestha | Sushant Pradhan Podcast
VIDEO: Can Hair Fall Be Prevented? | Dr Smriti Shrestha | Sushant Pradhan Podcast
VIDEO: Modern Skincare Trends You Should Know | Dr Smriti Shrestha | Sushant Pradhan Podcast
CHANNEL: UCZuKpNyipL9W-OkKwCMwVNQ
VIDEO: सुखी किसानका कथा | Sukhi Kisan ka Katha | Herne Katha EP169 - हेर्ने कथा
VIDEO: हावामा के छ - भाग २ | Hawama K Chha? | What is in the Air - Part 2 | हेर्ने कथा - Herne Katha
VIDEO: हात्ती पाल्नेका कथा | Hatti Palne ka Katha - The Elephant Savers | Herne Katha EP168 - हेर्ने कथा
VIDEO: हावामा के छ ? - भाग १ | What is in the Air? | Hawama K Chha? - EP 01 | Herne Katha -  हेर्ने कथा
VIDEO: मानियाको कथा  | Maniyako Katha | Herne Katha EP167 - हेर्ने कथा
VIDEO: पिएचडी किसानको कथा  | Story of a PHD Farmer | Herne Katha EP166 - हेर्ने कथा
VIDEO: छार्का स्कुल र सोनामको कथा  | Chharka School and Sonam | Herne Katha EP165 - हेर्ने कथा
VIDEO: बुढो बाघको कथा  | Story of the Old Tiger | Herne Katha EP164 - हेर्ने कथा
VIDEO: हेटौंडा कपडा उद्योगको कथा  | Hetauda Kapada Udhyogko Katha | Herne Katha EP163 - हेर्ने कथा
VIDEO: मगन्ताका कथा | Magantaka Katha | Herne Katha EP162 - हेर्ने कथा
CHANNEL: UCTm_ZE0j6Nahzkdp8tR5oKg
VIDEO: Who Killed Nepali Football?
VIDEO: The Shreepech Heist
VIDEO: Asia’s Deadliest Football Disaster
VIDEO: The Rise and Fall of GUNDARAJ
VIDEO: BALEN: The New MAHENDRA?
VIDEO: The Ride Sharing WAR of Nepal
VIDEO: अमेरिकी सेना नेपालमा? I The Dark Truth of SPP
VIDEO: TOP 3 BIGGEST BANK HEISTS IN NEPAL
VIDEO: NEPAL’S BIGGEST BLACK MONEY INVESTIGATION
VIDEO: The Real Power of Balen Shah &amp; His Ministers
CHANNEL: UCuv3IZ2RpS657pt5aL7TVtQ
VIDEO: Investor हरू डराएका हुन् कि ठूला खेलाडी Side लागेका हुन् ? Good vs Bubble Stocks NEPSE को असली कहानी
VIDEO: HRL-NRIC काण्ड : Nepal’s Biggest Stock Market Scam EXPLAINED |
VIDEO: ठूलो Business गर्न Nepal मा Setting चाहिन्छ ? Legacy Business मा Next Gen को Pressure कति ?
VIDEO: नेपालको ३० खर्ब ऋण, देश डुब्न लागेको हो? | Nepal&#39;s Debt Reality Check | खतरा कि व्यवस्थापन योग्य ?
VIDEO: सावधान! तपाईंको पुरानो Post ले Career, Visa र Reputation बिगार्न सक्छ |
VIDEO: Sovereign Wealth Fund: Future बन्ने Plan हो कि Budget को Fancy Word मात्र?Hydro लाई Gold बनाउन सक्छ?
VIDEO: AI सँगको जीवन | AI Explained | AI ले  job खाइदिन्छ ? AI introduction and Basics Explained - Part 1
VIDEO: Free Visa, Free Ticket कि Hidden Cost?विदेश रोजगारको सबैभन्दा ठूलो cost ticket होइन confusion हो.
VIDEO: Reality of Himalayan Java | Satik Kura EP 06 | Ideapreneur Nepal
VIDEO: नेपालमा Delivery Company धेरै छन्… तर Trust गर्ने कुन?
CHANNEL: UCJUFkLE5GjqloVigynCN4VA
VIDEO: The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता ! #TankaDahal #balenshah
VIDEO: सिस्टम बलियो बने देश बलियो बन्छ तर व्यक्ति बलियो बने तानाशाह जन्मिन्छ
VIDEO: एउटा लोकप्रिय नेताको ताना*शाह तर्फको यात्रा | Tanka Dahal
VIDEO: Why am I leaving Microsoft ? Something big is coming... | Tanka Dahal
VIDEO: The Truth : नेपालले जमिन मिचेकै हो त?  Border | India Nepal | Tanka Dahal
VIDEO: बोल्यो कि पोल्यो : बालेन साहको भाषणमा के छ त्यस्तो? । Tanka Dahal
VIDEO: The Truth : रिपोर्टमा के छ ? Media Trial VS Reality... | Tanka Dahal
VIDEO: गैर आवासीय नागरिकताको बास्तबिकता : Watch before you get NRN Citizenship ! [Podcast ]
VIDEO: अदालतमा राजनीतिको जालोको नालीबेली  ! Tanka Dahal
VIDEO:  अध्यादेश : बाध्यता, पेलान कि आवस्यकता ? [Analysis] | Tanka Dahal
CHANNEL: UCNBOwzQRaNho7OUZa7bFbDA
VIDEO: Galaxy A27 Review नेपालीमा: Don’t Buy the Wrong Samsung!
VIDEO: The Dark Side of Nepal&#39;s Second Hand Phone Market!
VIDEO: Realme&#39;s New Mid-Range Phone: Great Value or Overpriced?
VIDEO: OnePlus Nord 6 Unboxing &amp; Review नेपालीमा: Buy Or Skip?
VIDEO: I Gave 3 Teams रू 2.5 Lakh to Build the Ultimate PC in Nepal!
VIDEO: Best Phones Under Rs. 60,000 in Nepal - Buy it Before It&#39;s Too Late!
VIDEO: Best Phones Under 1 Lakh in Nepal - Don&#39;t Buy Wrong!
VIDEO: iPhone 18 Series Coming soon! iPhone 18 Pro Max, iPhone Fold!
VIDEO: Xiaomi 17T Unboxing &amp; Review नेपालीमा: ढिला आयो कडा आयो!
VIDEO: Honor 600 Pro Unboxing &amp; Review नेपालीमा: Buy Or Skip?
CHANNEL: UCskj1U7tvN6m7sZP7FAPpyQ
VIDEO: Best Phones to Buy Under ₹ 40,000 in 2026 - Don&#39;t Buy Wrong!
VIDEO: Samsung Galaxy A27 Review: Buy or Skip?
VIDEO: Galaxy Fit 3 vs Huawei Band 11 - Best Fitness Band under ₹5000?
VIDEO: JBL GO 5 Review: Better than JBL GO 4?
VIDEO: Ultimate Flagship Portrait Camera Comparison! - Who wins??
VIDEO: Best ANC Earbuds for INR 3000! - OPPO Enco Air5 #shorts
VIDEO: iPhone 17 Pro Max Vs Vivo X300 Ultra Portrait Video Comparison! #shorts
VIDEO: Xiaomi 17T Review: Don&#39;t Buy It Until You Watch This!
VIDEO: I Found a Good Everyday Laptop - Acer Aspire 5! #shorts
VIDEO: 10 Android 17 Features That Make iPhone Users Jealous!
CHANNEL: UCygzOsiHWgvOq5vNahSTehg
VIDEO: सीमा सुरक्षाको लागि ‘ड्रोन’ र ‘फेस रिकोग्निसन’ सीसीटिभी प्रयोग गर्ने सरकारको तयारी
VIDEO: बजार कसैले रोकेर रोकिँदैन !  || सेयर गफ ।।07/24/2026।। Yubaraj Bhusal , Sudha Devkota
VIDEO: प्रचण्डको टिप्पणी–‘हाम्रा कमजोरीमाथि टेकेर नेपाली जनतालाई ‘अफिम’ खुवाए’
VIDEO: हामी सडकमा प्रायः सबैलाई हतारमा देख्छौँः राजेश हमाल
VIDEO: विदेशमा पहिला अरुलाई, तर हाम्रोमा आफू पहिले जान खोज्ने प्रवृत्ति देखिन्छः मदनकृष्ण श्रेष्ठ
VIDEO: नेपाली कांग्रेस  | LIVE | Merolagani
VIDEO: शैक्षिक परामर्श नियमावलीमा देखिएका त्रुटी सच्याउन सरकार तयार
VIDEO: अख्तियारलाई राजनीतिक हस्तक्षेपमुक्त बनाउन संविधान संशोधन गर्न काँग्रेस तयारः गगन थापा
VIDEO: लोकतन्त्र ‘अपहरित’ भएको छ, पुनःस्थापना आवश्यकः ओली
VIDEO: बालेनले अर्थमन्त्री वाग्लेलाई भनेः पात्र जोसुकै होस् मलाई नतिजा दिनुस्
CHANNEL: UCjIxYB6uC6Eqx1Bq6eIf32g
VIDEO: सहिदपुत्र नेल्सनलाई अक्षय गोल्याणको मर्मस्पर्शी सन्देश
VIDEO: Mark Tolley Statement
VIDEO: Hamrobazaar Partners with Foneloan
VIDEO: Narendra Kumar Gupta,  Spokesperson of Shree Ridhi Sidhi Jewellers
CHANNEL: UCxCoea3ulOukfXiYAm87ZIA
VIDEO: बुहारी भाग - २८९ | BUHARI Episode -289 | कथा चेलीकाे | Nepali Sentimental Serial | 24th June 2026
VIDEO: Dilma Thau Chha || BEHULI Nepali Movie Song 2026 || Cool Boy (Paras Bam Thakuri), Divya Rayamajhi
VIDEO: HALEE | Movie Official Trailer 2026 | Pramod Deep, Sujata Thapa, Om Prateek (Gurung), Saroj Khanal
VIDEO: Putpute Nach || BAN PHOOL Movie Song 2026 (Gurung Culture Movie) || Mausam Gurung, Jonisha Gurung
VIDEO: Nepali Serial Juthe (जुठे) S2 || Episode 259 || July 22nd - 2026 By Marichman Shrestha, Rabi Giri
VIDEO: साथी आएपछी घरमा हङ्गामा | Jwai Saab (ज्वाइँसाब) भाग-34 (Epi 34) | Natural Comedy | Pawan Khatiwada
VIDEO: Nepal Ko Naam Le || Sumit Khadka || SP Koirala || New Nepali National Song 2026 || Niraj Shrestha
VIDEO: Timi Mero Sanjeevani || KAMALA MISS Movie Song 2026 || Basana Timilsina, Aarav Dahal, Shivam Saraf
VIDEO: SAMJHAUTA || Episode 5 &quot;सम्झौता&quot; || New Nepali Serial || Sarita Dhungana, AK Arjun, Sneha, Tek, Gita
VIDEO: Oii Oii Chameli | CHAMELI KO POI Movie Song 2026 | Surakshya Panta, Narayan Tripathi, Wilson Bikram
CHANNEL: UCNR1KcWXj7zpWQFJtU3ddYg
VIDEO: Any Problen! - Lily Bily #bsd #love #drama #sad #nepalimovie #shorts
VIDEO: छुच्ची सासु भाग-१२७ | Chhuchchi Sasu Ep 127 | परिवारको कथा | Nepali Sentimental Serial July 23 2026
VIDEO: Nai Nabhannu La 3  #nepalimovie #love #drama #romantic #shorts #fyp
VIDEO: Maya Vaneko Yesto Hola | Day 6 | Official Behind the Scenes | In Cinemas September 11, Bhadra 26
VIDEO: Maya Vaneko Yesto Hola | Day 6 | Official Behind the Scenes | In Cinemas September 11, Bhadra 26
VIDEO: नारी भाग - २५१ | Naari Episode -251 | प्रत्येक चेलीको कथा | Nepali Sentimental Serial. July 20 2026
VIDEO: Outlaw Dafa 219  - Full Movie on Cinemaghar - 2025 - Sushil Shrestha, Shikshya Sangroula
VIDEO: छुच्ची सासु भाग-१२६ | Chhuchchi Sasu Ep 126 | परिवारको कथा | Nepali Sentimental Serial July 16 2026
VIDEO: नारी भाग - २४० | Naari Episode -240 | प्रत्येक चेलीको कथा | Nepali Sentimental Serial. May 4 2026
VIDEO: Out Now Lil Jhola - ANNA Ft. Yoku BIG ( OFFICIAL SONG )  #liljhola  #fypnepal #trend #rap #nepalirap
CHANNEL: UCrzyJYtjLOTfnUur8hsr7ow
VIDEO: गाउ कै राम्री म - Khyal Thatta Comedy #shorts #comedy
VIDEO: Khyal Thatta &quot;ख्याल ठट्टा&quot; - Ep 83 || Nepali Comedy Serial | Suraj Khanal, Sabita Gurung, Dipa Shahi
VIDEO: यो घर छोडेर गै हाल - Aama Sabaiki S2 Nepali Serial #shorts #drama
VIDEO: बाउ आमा को टुंगो नभएको - Aama Sabaiki S2 Nepali Serial #shorts #drama
VIDEO: तिमि फर्केर आउने आश छ - Aama Sabaiki S2 Nepali Serial #shorts #drama
VIDEO: अब हामि बिहे गर्न पर्छ - Aama Sabaiki S2 Nepali Serial #shorts #drama
VIDEO: मैले बिहे गरे आमा - Aama Sabaiki S2 Nepali Serial #shorts #drama
VIDEO: बा आमा बिना बिहे गर्दिन - Aama Sabaiki S2 Nepali Serial #shorts #drama
VIDEO: AAMA SABAIKI S2 Ep 02 || Chhora Mare Pachhi Buhari Lai Hela || Nepali Serial
VIDEO: माफी माग्न आको - Bhabiko Lekhant Scene #shorts #drama
CHANNEL: UC87bT8uMZMUUqitTTTsESbA
VIDEO: नेपाल भलिबल लिगको टोली कर्णाली शिवराजको ब्रान्ड एम्बेसडर घोषित भएपछि महानायक राजेश हमाल
VIDEO: नेपाल भलिबल लिगको टोली कर्णाली शिवराजको क्विन अफ कर्णाली घोषित भएपछि प्रगति नाथ
VIDEO: नेपाल भलिबल लिगको टोली कर्णाली शिवराजको ग्लोरी अफ कर्णाली घोषित भएपछि सुमित्रा रेग्मी
VIDEO: नेपाल भलिबल लिगको टोली कर्णाली शिवराजको क्विन अफ कर्णाली घोषित भएपछि कामना विष्ट
VIDEO: Bhola Silwal - Former Footballer | Hamro KhelCast E155 | भोला सिलवाल
VIDEO: पूर्वेली फुटबलका हस्ती दिलीप राईबारे पूर्व खेलाडी तथा प्रशिक्षक भोला सिलवाल
CHANNEL: UC2-AXj9DqhAHEaOnfACTUDw
VIDEO: The Plan That Could Change Kathmandu Forever
VIDEO: The Picnic That Ended Rana Rule
VIDEO: How Nepal Lost Limpiyadhura...Forever | EON
VIDEO: अध्यादेश भनेको के हो? What is an ordinance?
VIDEO: This Oil Shock Is About To Hit Nepal | EON
VIDEO: How Kathmandu&#39;s Sukumbasi Settlement Changed Over Time?
VIDEO: This is how petrol and diesel are actually made.
VIDEO: How Getting Sick in Nepal Will Ruin You Financially?
VIDEO: Balen — The Most Powerful PM in Nepal&#39;s History? | EON
VIDEO: One Final Message Before The Election
CHANNEL: UCoRqrpx9zDD9U331P53wOnw
VIDEO: #trailer What&#39;s With Dohori Industry of Nepal?
VIDEO: Go Rabindra Dhatt 👊
VIDEO: Singer Vs Comedians Income. Watch full episode on YouTube: What’s With Top Comedians of Nepal
VIDEO: Bishal Gautam Sharing his iconic moment on What’s With Roundtable. Watch full episode. What’s With
VIDEO: #whatswith
VIDEO: Sandip Praised Samdhi #whatswith
VIDEO: #whatswith
VIDEO: Apporva on being Comedian @apoorwakshitizsingh
VIDEO: Anil Shah Charges 1 Lakh per session  #whatswith #financialmarket
VIDEO: Why Bishal Gautam entered Comedy Industry? @Bishal3437
CHANNEL: UCnvSIXKLV9hPmH2TPtjlzPw
CHANNEL: UCnm1YlY-DWrxHB0FVDXRnag
VIDEO: १६ खर्ब राजस्व उठाउने अर्थमन्त्रीको मिसन, ट्रयापमा जनता ।।  Mission 16 Kharba
VIDEO: ५ लाख विद्यार्थीको सातो उडाउने एउटा सरकारी निर्णय ।। Loksewa exam
VIDEO: कांग्रेसमा कसले लेख्दैछ फुटको स्क्रीप्ट ? ।। Congress Crisis Explained
VIDEO: बालेन र स्वर्णिमबीच किन बढ्यो टकराब ? Balen-Swarnim Relation Explained
VIDEO: शहरको बीचमा यति भव्य मैदान कसरी बन्यो ? ।। Pepsicola Football Ground
VIDEO: स्वर्णिमले मानेका थिएनन्, बालेनले उल्टाइदिए शिक्षा र स्वास्थ्यको कर ।। Removed Tax Explained
VIDEO: जनकपुर चुरोट र याक ब्राण्ड हडप्ने प्रपञ्च, कसरी जोगिए मालपानी ? ।। Exposed
VIDEO: ७५ अर्बको आत्मनिर्भर कुखरा-अण्डा बजार ।। Poultry Farming in Nepal
VIDEO: सेनालाई हेटौंडा कपडा उद्योगको तालाचाबी, किन सजिलो छैन चलाउन ? ।। Hetauda Kapda Udhyog
VIDEO: नेपालीलाई भुटानी शरणार्थी बनाएर अमेरिका पठाउने धन्दाको कथा ।| Bhutan Refugee Scam Explained
CHANNEL: UCSqetNaur-z6CU9EdTV0GPw
VIDEO: इरानको नयाँ प्रबिधिले तनाबमा अमेरिका || How Iran Hit Secret CIA Stations: The Russian Kometa-M Tech
VIDEO: के ढल्न लागेको हो मोदी सरकार? || After Sri Lanka, Bangladesh &amp; Nepal, Is India Next?
VIDEO: अमेरिकी योजना र इरानको काउन्टर-प्लान || Inside Iran’s Pickaxe Mountain Nuclear Bunker
VIDEO: इरानको डान्सिङ मिसाइलले जोर्डनमा बिध्वंस || Iran&#39;s &#39;Dancing Missiles&#39; Devastate US Hub in Jordan
VIDEO: अमेरिकी प्रहार र इरानको जवाफ || Is the Iran-US War Turning Into a Civilian Crisis?
VIDEO: रुस र चीनको नयाँ युद्ध रणनीति || Inside the Shocking Russia-China War Strategy
VIDEO: खाडिमा इरानको मिसाइलको बर्षा || Trump’s 21-Day Red Line for the Middle East!
VIDEO: रुस र चीनको गोप्य मास्टर प्लान ||Digital Superweapons: The Hidden Space Battle Reshaping Modern Wars
VIDEO: आधुनिक इतिहासकै सबैभन्दा विशाल शवयात्रा || Why the Supreme Leader’s Funeral Entered Iraq
VIDEO: मोसादको योजना न्यूयोर्क टाइम्सको खुलासा || Where is Iran&#39;s new Supreme Leader, Mojtaba Khamenei?

,channel,video,video_id,comment,published_at
0,UC2rariKhGBaLf0qmhWQv3KQ,Nepal&#39;s First Modern Tunnel? l RONB Expla...,XnPOuwslU5o,Aba Balen ley surung marga ma chai k nei garer...,2026-07-26T02:29:19Z
1,UC2rariKhGBaLf0qmhWQv3KQ,Nepal&#39;s First Modern Tunnel? l RONB Expla...,XnPOuwslU5o,Dai affno sathi ko pani kae galati oulauni hok...,2026-07-25T18:45:31Z
2,UC2rariKhGBaLf0qmhWQv3KQ,Nepal&#39;s First Modern Tunnel? l RONB Expla...,XnPOuwslU5o,So sad to hear this why they not content Nepal...,2026-07-25T16:57:04Z
3,UC2rariKhGBaLf0qmhWQv3KQ,Nepal&#39;s First Modern Tunnel? l RONB Expla...,XnPOuwslU5o,केपि oli को vision ले गर्दा यो सम्भव भएको हो। ...,2026-07-25T09:44:08Z
4,UC2rariKhGBaLf0qmhWQv3KQ,Nepal&#39;s First Modern Tunnel? l RONB Expla...,XnPOuwslU5o,कमसेकम थम्बनेलमा त केपी को फोटो राखओ ए गँजेडी ...,2026-07-25T04:44:40Z

## Mark Devnagari, Roman or english

In [19]:
import re
from wordfreq import zipf_frequency

# Detect Devanagari Unicode
DEVANAGARI_PATTERN = re.compile(r'[\u0900-\u097F]')

def detect_language(text):
    text = str(text).strip()

    if not text:
        return "unknown"

    # 1. Devanagari Nepali
    if DEVANAGARI_PATTERN.search(text):
        return "devanagari_nepali"

    # Extract alphabetic words
    words = re.findall(r"[a-zA-Z']+", text.lower())

    if len(words) == 0:
        return "unknown"

    # Count how many words look like English
    english_count = sum(
        zipf_frequency(word, "en") > 3
        for word in words
    )

    ratio = english_count / len(words)

    # Mostly English words
    if ratio >= 0.7:
        return "english"

    # Otherwise assume Roman Nepali
    return "roman_nepali"

In [20]:
yt_comments["clean_comment"] = yt_comments["comment"].apply(clean_text)
# Remove with low length
yt_comments = yt_comments[
    yt_comments["clean_comment"].str.split().str.len() >= 8
].reset_index(drop=True)# remove nan vals and save
yt_comments = yt_comments.dropna()
yt_comments = yt_comments[yt_comments["comment"]!=""]
# label languate
yt_comments["language"] = yt_comments["comment"].apply(detect_language)
# random state shuffle
yt_comments = yt_comments.sample(frac=1, random_state=41)

# show data
print(f"Total Length of data = {yt_comments.shape}")
yt_comments.head()

Total Length of data = (9136, 7)

,channel,video,video_id,comment,published_at,clean_comment,language
3272,UCZuKpNyipL9W-OkKwCMwVNQ,हावामा के छ ? - भाग १ | What is in the Air? | ...,R1c27P_gG5k,Main concern of this Time Adverse effects of ...,2026-06-05T16:49:08Z,main concern of this time adverse effects of i...,english
5192,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,बालेनको स्थानीय सरकारको भूमिका प्रशंसनीय रह्यो...,2026-07-19T04:58:31Z,बालेनको स्थानीय सरकारको भूमिका प्रशंसनीय रह्यो...,devanagari_nepali
579,UC2CAM55AnDflrpC20uH700A,Nepali OTT&#39;s Biggest Bet Ever | WSO | Bina...,-XN_V4ebOGc,Money making tournament bhayera ta fifa presi...,2026-07-18T07:05:13Z,money making tournament bhayera ta fifa presid...,roman_nepali
4177,UCZuKpNyipL9W-OkKwCMwVNQ,हेटौंडा कपडा उद्योगको कथा | Hetauda Kapada Ud...,7PgE0tLgSF8,हेर मेरो देस को बिजोक अब चल्न्नु पर छ ।।।,2026-04-12T16:42:26Z,हेर मेरो देस को बिजोक अब चल्न्नु पर छ ।।।,devanagari_nepali
3496,UCZuKpNyipL9W-OkKwCMwVNQ,पिएचडी किसानको कथा | Story of a PHD Farmer | ...,38NauB4dMec,चकलाबंदी गरे र मात्र देश को खेती र खाद्यान्न म...,2026-05-23T07:29:11Z,चकलाबंदी गरे र मात्र देश को खेती र खाद्यान्न म...,devanagari_nepali

In [21]:
# youtube comments saved
yt_comments.to_csv("./datasets/yt_comments.csv", index=False)