# Handling Data for Nepali Post Sentiment Analysis

Following datasets will be used for sentiment analysis of emotions in different posts online. 
- https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv
- https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv
- https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv

This dataset is choosen to let model understand different emotion via texts. This will allow us to get information on emotion or sentiment of human writing a post. Also the data from reddit where Nepali people posts will be collected and categorized and analysed using KMeans then again feed to the senitment analysis to get overall picture of nepali people's discussion and their emotions regarding it.

## Download GoEmotions dataset

### import libraries 
- request
- pandas

In [26]:
import requests
import pandas as pd 
import os

In [27]:
go_emotion_base_url = "https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/"

# go emotion datasets names
go_emotion_datasets_names = [
    "goemotions_1.csv",
    "goemotions_2.csv",
    "goemotions_3.csv"
]

# make an empty list to append loaded pd
go_emotions_list = []

# use loop for goemotion
for goemotion in go_emotion_datasets_names:
    df = pd.read_csv(f"{go_emotion_base_url}{goemotion}")
    go_emotions_list.append(df)
    print(f"{goemotion} Loaded!")
    
go_emotions_dataset = pd.concat(go_emotions_list, ignore_index=True)

print(f"SHAPE OF FINAL GO_EMOTION DATASET = {go_emotions_dataset.shape}")
go_emotions_dataset.head(3)

goemotions_1.csv Loaded!
goemotions_2.csv Loaded!
goemotions_3.csv Loaded!
SHAPE OF FINAL GO_EMOTION DATASET = (211225, 37)

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,eew5j0j,Brdd9,nrl,t3_ajis4z,t1_eew18eq,1.548381e+09,1,False,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,eemcysk,TheGreen888,unpopularopinion,t3_ai4q37,t3_ai4q37,1.548084e+09,37,True,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",ed2mah1,Labalool,confessions,t3_abru74,t1_ed2m7g7,1.546428e+09,37,False,0,...,0,0,0,0,0,0,0,0,0,1

## Clean GoEmotions Data as per Needed:
- remove id, author, subreddit, link_id, parent_id, created_utc and rater_id, example_very_unclear
- clean text column (text preprocessing)

In [28]:
# drop unnecessary columns
go_emotions_dataset.drop(columns=[
    "id", "author", "subreddit", "link_id", 
    "parent_id", "created_utc", "rater_id", 
    "example_very_unclear"
], inplace=True)

print("Dropped unnecessary columns in place!")

Dropped unnecessary columns in place!

### Clean text requires additional libraries:
- regex
- bs4 BeautifulSoup
- string

Create a function to clean text usable in future as well. This function will remove html, punctuations, urls, additonal spaces, emojis, and also lowercase the text. It is required as a basic pre-processing for TF-IDF NLP.

In [29]:
import re
import string
from bs4 import BeautifulSoup
import emoji


# function to clean and direct apply
def clean_text(text):
    # remove html
    text = BeautifulSoup(text, "html.parser").get_text()
    # remove punctuation
    text = re.sub(r"[^\w\s]", "", text)
    # remove multiple spaces
    text = re.sub(r"\s+", " ", text).strip()
    # remove urls
    text = re.sub(r"http\S+|www\S+", "", text)
    # remove emoji
    text = emoji.replace_emoji(text, "")
    # return
    return text.lower().strip()

In [30]:
# Apply the function to text column
go_emotions_dataset["text"] = go_emotions_dataset["text"].apply(clean_text)

# See few texts how  they look
go_emotions_dataset.head()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,that game hurt,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,sexuality shouldnt be a grouping category it m...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,you do right if you dont care then fuck em,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,man i love reddit,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,name was nowhere near them he was by the falcon,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

### Drop null values if any and Save

In [31]:
# Drop na value and save
go_emotions_dataset = go_emotions_dataset.dropna(subset=["text"]).reset_index(drop=True)

go_emotions_dataset.isna().sum()

text              0
admiration        0
amusement         0
anger             0
annoyance         0
approval          0
caring            0
confusion         0
curiosity         0
desire            0
disappointment    0
disapproval       0
disgust           0
embarrassment     0
excitement        0
fear              0
gratitude         0
grief             0
joy               0
love              0
nervousness       0
optimism          0
pride             0
realization       0
relief            0
remorse           0
sadness           0
surprise          0
neutral           0
dtype: int64

In [33]:
# Save to the datasets folder
go_emotions_dataset.to_csv("./datasets/go_emotions.csv", index=False)

## Download YT Comments
This data will be downloaded googles Youtube API key. This dataset will contain nepali's voice including youths. The comments represent what nepali people think on current government, system, justice, education, etc. This shows if citizens are happy or not in different aspects of the country.

### Import Libraries
- build from googleapiclient.discovery
- dotenv
- LangDetectException

In [7]:
from dotenv import load_dotenv
from googleapiclient.discovery import build
from langdetect import detect, LangDetectException

# config dotenv
load_dotenv("./.env")

True

In [8]:
# youtube api key access
youtube = build(
    "youtube",
    "v3",
    developerKey=os.getenv("YT_API_KEY")
)

### Extracts channel ID
The channel id is not usually present like it used to, so it is necessary to extract the channel's id before extracting contents from the Api.

In [9]:
def get_channel_id(channel):

    # Already a channel ID
    if channel.startswith("UC"):
        return channel


    # Handle (@name)
    if channel.startswith("@"):

        response = youtube.channels().list(
            part="id",
            forHandle=channel.replace("@","")
        ).execute()


        if not response.get("items"):
            raise Exception(
                f"Channel not found: {channel}"
            )

        return response["items"][0]["id"]

    raise Exception(
        f"Invalid channel format: {channel}"
    )

### Selection of Channels
Only few channels are selected:
- TechTanka
- WhySoOffend
- Thaharesearch
- eon_visuals
- TheNepaliComment

These channels are popular in the youtube explaining current problems and news of Nepal. They also talk about: politics, corruption, system, justice, etc which brings engaging viewrs on the video who comment and share their point of view.

In [10]:
channels = [
    get_channel_id("@TechTanka"),
    get_channel_id("@WhySoOffended"),
    get_channel_id("@Thaharesearch"),
    get_channel_id("@eon_visuals"),
    get_channel_id("@TheNepaliComment")
]

### Extract playlists and recent videos

In [11]:
def get_upload_playlist(channel_id):

    response = youtube.channels().list(
        part="contentDetails",
        id=channel_id
    ).execute()
    return response["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]

In [12]:
def get_recent_videos(
    channel_id,
    start_date,
    end_date,
    limit=10
):
    response = youtube.search().list(
        part="snippet",
        channelId=channel_id,
        order="date",
        maxResults=limit,
        type="video",
        publishedAfter=start_date,
        publishedBefore=end_date
    ).execute()

    videos=[]

    for item in response.get("items", []):

        videos.append({
            "video_id": item["id"]["videoId"],
            "title": item["snippet"]["title"],
            "date": item["snippet"]["publishedAt"]
        })

    return videos

### Recieve Comments
This function is the main function used internally to fetch all the comments in the video.

In [13]:
def get_comments(video_id, limit=500):

    comments=[]
    
    request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        maxResults=100,
        textFormat="plainText"
    )

    while request and len(comments) < limit:
        try:
            response = request.execute()
        except:
            break

        for item in response["items"]:
            snippet = (
                item["snippet"]
                ["topLevelComment"]
                ["snippet"]
            )

            comments.append({
                "comment": snippet["textDisplay"],
                "published_at": snippet["publishedAt"]
            })

        token = response.get("nextPageToken")

        if token:
            request = youtube.commentThreads().list(
                part="snippet",
                videoId=video_id,
                pageToken=token,
                maxResults=100,
                textFormat="plainText"
            )
        else:
            break
        
    return comments

### Quality control of Comments
This function only passes the quality comments. The quality control must fullfill following criteria for passing:
- Language must be English (NO-Devnagari)
- Length of raw text must be above 5
- Remove low value adding phrases

No-devnagari because devnagari will add additional challange to preprocess, meaning extraction and also creates larger groups for model's embedding to understand. Also there are limitations on semantic datasets for devnagari (NEPALI). This will also affect K-Means Clustering as the model might just seperate Devnagari embedding to a seperate chunk not giving approprite meaning with english embeddings.

Length of text must be above 5 because raw text too short might give lower semantic value. This does not give detail emotion on how person relates and feels, a simple " I have done this ..... and ..... which caused me to be depressed." structured is needed instead of "I am very sad." For model to generalize well.

Removal of useless phrases simply means removing comments that contains low value adding texts such has : nice video, wow, upload more, etc. as this does not align with the project's problem and rather focus on what people are talking about video not problem.

In [14]:
def is_quality_comment(text):
    try:
        if detect(text) != "en":
            return False
        
    except LangDetectException:
        return False

    if len(text.split()) < 10:
        return False

    low=text.lower().strip()

    useless = [
    # talking about the video quality itself
    "nice video",
    "great video",
    "awesome video",
    "amazing video",
    "excellent video",
    "good video",
    "very good video",
    "best video",
    "cool video",
    "beautiful video",
    "wonderful video",
    "fantastic video",
    "brilliant video",
    "incredible video",
    "interesting video",
    
    # talking about content without adding information
    "nice content",
    "great content",
    "awesome content",
    "amazing content",
    "good content",
    "best content",
    "love this content",
    "loved this content",

    # generic creator appreciation
    "thanks for the video",
    "thank you for the video",
    "thanks for uploading",
    "thanks for sharing",
    "thank you for sharing",
    "thanks for making this",
    "appreciate the video",
    "appreciate this video",

    # generic reactions
    "nice one",
    "good one",
    "great one",
    "awesome one",
    "well done",
    "good job",
    "great job",
    "awesome job",

    # Engagement spam
    "first",
    "first comment",
    "early",
    "early gang",
    "who is watching in 2026",
    "anyone here in 2026",
    "still watching",
    "watching in 2026",

    # Requests without discussion
    "make more videos",
    "more videos please",
    "upload more",
    "keep uploading",
    "keep making videos",
    "keep it up",
]

    for phrase in useless:
        if phrase in low:
            return False

    return True

### The main Scrape Function
Extracts video -> Extracts Comment -> Checks Quality -> Use/Throw

In [15]:
def scrape_channels(channels, start_date, end_date, limit):

    data=[]

    for channel_id in channels:
        print("CHANNEL:", channel_id)
        videos=get_recent_videos(
            channel_id,
            start_date,
            end_date,
            limit
        )
        
        for video in videos:
            print(
                "VIDEO:",
                video["title"]
            )
            comments=get_comments(
                video["video_id"]
            )
            for comment in comments:
                if is_quality_comment(comment["comment"]):
                    data.append({
                        "channel":channel_id,
                        "video":video["title"],
                        "video_id":video["video_id"],
                        "comment":comment["comment"],
                        "published_at":comment["published_at"]
                    })

    return pd.DataFrame(data)

In [16]:
yt_comments = scrape_channels(channels, "2024-01-01T00:00:00Z", "2026-07-25T00:00:00Z", 80)
yt_comments.head()

CHANNEL: UCJUFkLE5GjqloVigynCN4VA
VIDEO: The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता ! #TankaDahal #balenshah
VIDEO: सिस्टम बलियो बने देश बलियो बन्छ तर व्यक्ति बलियो बने तानाशाह जन्मिन्छ
VIDEO: एउटा लोकप्रिय नेताको ताना*शाह तर्फको यात्रा | Tanka Dahal
VIDEO: Why am I leaving Microsoft ? Something big is coming... | Tanka Dahal
VIDEO: The Truth : नेपालले जमिन मिचेकै हो त?  Border | India Nepal | Tanka Dahal
VIDEO: बोल्यो कि पोल्यो : बालेन साहको भाषणमा के छ त्यस्तो? । Tanka Dahal
VIDEO: The Truth : रिपोर्टमा के छ ? Media Trial VS Reality... | Tanka Dahal
VIDEO: गैर आवासीय नागरिकताको बास्तबिकता : Watch before you get NRN Citizenship ! [Podcast ]
VIDEO: अदालतमा राजनीतिको जालोको नालीबेली  ! Tanka Dahal
VIDEO:  अध्यादेश : बाध्यता, पेलान कि आवस्यकता ? [Analysis] | Tanka Dahal
VIDEO: सुकुम्बासी समस्या कि खोला किनारको राजनीति ? (Reupload)
VIDEO: सिंगापुरमा यस्तो, नेपालमा कस्तो? बालेन बन्लान त ली क्वान? | Tanka Dahal #singapore #nepal
VIDEO: Truth behind the report... | Tanka Dahal
VIDEO: [Part - 1] : MCC - The Truth and the Conspiracy !  | Tanka Dahal | #MCC
VIDEO: Nepal Election 2082 : रास्वपाको दुई-तिहाईको भित्रि अर्थ  । Tanka Dahal
VIDEO: Fall and Rise of the लुसिफर : सडकदेखि प्रधानमन्त्रि सम्मको यात्रा । Tanka Dahal | #balenshah
VIDEO: System Capture  - कसरी ठीक गर्ने ? चुनाव अघि हेर्ने पर्ने भिडियो। Tanka Dahal
VIDEO: पहिला २३ आयो कि २४ आयो ? के भएको थियो त्यो दिन ? चुनाव अघि हेर्नै पर्ने भिडियो (reupload)
VIDEO: यसकारण हुदैछ यो सब : समसामयिक बिषयमा स्वागत नेपालसँग भएको कुराकानी । Tanka Dahal
VIDEO: The Truth : अमेरिकी सेना जेनजी सरकारले नेपाल छिराएकै हो त ? ।  TankaDahal
VIDEO: नेपाली मिडिया र राजनीतिज्ञले यो कुरा किन गर्दैनन्? (Analysis) । Tanka Dahal |#Bangladesh
VIDEO: होली वाइन काण्डको चुहिएको डकुमेन्टमा के छ ? चुनावमा बिदेशी चलखेलको अर्को अध्याय... ।  Tanka Dahal
VIDEO: Can Gagan Thapa be the next PM? सर्लाही-४ बाट कसले जित्छ र कसरी ?  With Data | Tanka Dahal
VIDEO: झापा-५ बाट बालेन या ओली ? यस कारण हुनेछ जित-हार  | Tanka Dahal
VIDEO: राजसंस्था, राजनीति र रमिता : Special talk with Rabindra Mishra । Tanka Dahal
VIDEO: Trailer : राजसंस्था, राजनीति र रमिता : Special talk with Rabindra Mishra
VIDEO: USA vs Venezuela : ६ वटा कोणबाट बुझौ समस्याको जरो... | Tanka Dahal |#USA #Venezuela
VIDEO: जेनजी आन्दोलनको दिन के भयो ? बालेन, रवि र कुलमान कसरि मिले ?  [Podcast with Gen-Z Rishi Thapa]
VIDEO: रिलायन्स स्पिन्निङ्ग मिल्स (पवन गोल्यान) को IPO काण्ड : बित्तिय अपराध हो कि होइन ?
VIDEO: जेनजीलाई प्रयोग गरेर जेनजीमाथि नै षडयन्त्र हुँदैछ, सब जेल जानेछन !
VIDEO: नेता चाही बिदेसमा उपचार गराउने, जनता चाही सिटामोल नपाएर मर्ने, के यहि हो काँग्रेसको समाजबाद?
VIDEO: यसरी गरिन्छ ब्रेनवास : Part of discussion with Chandra Bhandari
VIDEO: राजनीति, राजसंस्था, बिपी, काँग्रेस र भ्रष्टाचार : कांग्रेस नेता चन्द्र भण्डारीसँगको बिशेष कुराकानी !
VIDEO: Trailer : नेपाली काँग्रेसका नेता चन्द्र भण्डारी ज्युसँग भएको बिशेष कुराकानीको एक अंश।
VIDEO: भिजिट भिषा काण्ड : यसरी भएको थियो भ्रष्टाचार  | Tanka Dahal | Visit Visa
VIDEO: जेनजीको फरक धार : बिद्रोह हाइज्याक भयो ! हाम्रो बोली मुलधारले समेत डम्प गरिदियो।
VIDEO: पोखरा एयरपोर्ट भ्रस्टाचार : कसले, कसरी, कति र कहिले खाए ? [ Reupload ] | Tanka Dahal
VIDEO: धुर्मुस-सुन्तली-रेणु-रंगशाला : राजनीति कि पैसाको खेल? प्रमाण सहितको चिरफार | Tanka Dahal
VIDEO: Who is Real Lucifer in Nepal? | Tanka Dahal
VIDEO: गो*लि कहाँबाट हानियो ?  सेनाको अफिसमा के भयो ?  कसले के खेल्यो ?  जेनजीकै मुखबाट सुन्नुस !
VIDEO: प्रशासनले २३ वर्षसम्म लुकाएको अपराधको पर्दाफास !  न्याय खोइ ?  | Tanka Dahal
VIDEO: Social Cause: किड्नी रोगको नि:शुल्क उपचार - आउनुस मिलेर काम गरौ !
VIDEO: Podcast: हाम्रै मान्छेहरु भ्रष्ट छन् , आफ्नैले आफ्नै घर जलाए, दोष अरुलाई लगाए - Sunil Sharma, NC
VIDEO: Trailer : नेताहरु कै गल्तिको कारण आजको दिन आएको हो - डा सुनिल शर्मा (पूर्व सांसद, नेपाली काँग्रेस)
VIDEO: जेनजी आन्दोलन मोड्न कसले फैलाउदैछ भ्रम ?
VIDEO: Gen-Z : त्यो दिन के भएको थियो ? दोषि को? घटनाक्रम विश्लेषण सहित ...
VIDEO: Podcast : को हो एजेन्ट ? दुर्गा प्रसाईले देखाएका प्रमाण भित्र के के छन् ?
VIDEO: Trailer : दुर्गा प्रसाईले देखाएका प्रमाण भित्र के के छन् ?
VIDEO: [Podcast] संसदका महासचिवको दोहोरो नागरिकता र पासपोर्टको बास्तबिकता के हो ?  सुन्नुस उनकै मुखबाट !
VIDEO: सिंहदरबार जल्दा समेत सेनाले किन जोगाएन ? भित्रि र बाहिरी चलखेलको चिरफार ...
CHANNEL: UC2CAM55AnDflrpC20uH700A
VIDEO: SKILLS are the NEW DEGREE! | WSO | Binayak Kuikel
VIDEO: Nepali OTT&#39;s Biggest Bet Ever | WSO | Binayak Kuikel
VIDEO: What If 100 INR = 100 NPR? | WSO | Binayak Kuikel
VIDEO: Balen&#39;s Blunder or Strategic Move? | WSO | Binayak Kuikel
VIDEO: Karki Aayog Vs. Human Rights Commission Report | WSO | Binayak Kuikel
VIDEO: The Quietest Prime Minister EVER!! | WSO | Binayak Kuikel
VIDEO: NOC: ALWAYS ON LOSS!! Here’s Why | WSO | Binayak Kuikel
VIDEO: Balen Government After 30 DAYS | WSO | Binayak Kuikel
VIDEO: Why are they Fighting for JUSTICE? | WSO | Binayak Kuikel
VIDEO: The man who Secretly CONTROLLED Nepal | WSO | Binayak Kuikel
VIDEO: This Conflict HITS NEPALI Pockets!! | WSO | Binayak Kuikel
VIDEO: RSP Ministers: Qualified Enough? | WSO | Binayak Kuikel
VIDEO: Oli-Lekhak ARRESTED! | Karki Aayog Report | WSO | Binayak Kuikel
VIDEO: HISTORIC WIN! What NOW??  | WSO | Binayak Kuikel
VIDEO: RSP&#39;s MASTERPLAN  | WSO | Binayak Kuikel
VIDEO: Open Letter to RSP | WSO | Binayak Kuikel
VIDEO: Women in Politics: Then vs Now | WSO | Binayak Kuikel
VIDEO: Gen-Z Candidates vs Political Giants!!  | WSO | Binayak Kuikel
VIDEO: Harka Sampang : NEXT PRIME MINISTER?? | WSO | Binayak Kuikel
VIDEO: Two WOMEN: One BATTLE! | WSO | Binayak Kuikel
VIDEO: Loud and Clear!
VIDEO: JHAPA-5: ULTIMATE SHOWDOWN | WSO | Binayak Kuikel
VIDEO: KULMAN GHISING: What went WRONG? | WSO | Binayak Kuikel
VIDEO: USA vs VENEZUELA Explained!  | WSO | Binayak Kuikel
VIDEO: RISE OF GOLD EXPLAINED !! | WSO | Binayak Kuikel
VIDEO: KP Oli’s BIGGEST THRE*T EVER!!| WSO | Binayak Kuikel
VIDEO: WHY is RAJENDRA KHADGI like THIS? | WSO | Binayak Kuikel
VIDEO: GenZ Agreement: The 10 Points You Must Know | WSO | Binayak Kuikel
VIDEO: 2082 ELECTION: Who will RISE?? | WSO | Binayak Kuikel
VIDEO: The Mamdani Legacy: Can Nepali Politics Create a Successor? | WSO | Binayak Kuikel
VIDEO: Nepal CAN&#39;T produce NEEDLES, Here&#39;s WHY | WSO | Binayak Kuikel
VIDEO: 40 CRORE+ REVENUE! : The BUSINESS of Nepal Premier League | WSO | Binayak Kuikel
VIDEO: In search of a HERO! | नायक खोजिरहेको देश! | WSO | Binayak Kuikel
VIDEO: What are they COOKING? | WSO | Binayak Kuikel
VIDEO: Why Do Women Face THIS?? | Patriarchy with Wi-Fi | WSO | Binayak Kuikel
VIDEO: WTF is Lil Jhola? | WSO | Binayak Kuikel
VIDEO: Who PAYS? Understanding Insurance Business | WSO | Binayak Kuikel
VIDEO: GEN-Z PROTEST - HOW DID WE GET HERE? | WSO | Binayak Kuikel
VIDEO: THINGS TO KNOW ABOUT INTERIM GOVERNMENT (Recorded Instagram Live) | WSO | Binayak Kuikel
VIDEO: FACEBOOK FINALLY BANNED in Nepal? | WSO | Binayak Kuikel (Re-Upload)
VIDEO: Jaari 2: NEXT BLOCKBUSTER?  | WSO | Binayak Kuikel
VIDEO: END of Bidya Devi Bhandari&#39;s Political CAREER?  | WSO | Binayak Kuikel
VIDEO: How is DEUBA still POWERFUL??  | WSO | Binayak Kuikel
VIDEO: BUSINESS OF COLLABORATION | WSO | Binayak Kuikel
VIDEO: Nepal Needs JUSTICE | WSO | Binayak Kuikel
VIDEO: Society H*tes THEM, WHY?? | WSO | Binayak Kuikel
VIDEO: Vehicle STRIKE Explained! | WSO | Binayak Kuikel
VIDEO: Will FACEBOOK be Banned in Nepal? | WSO | Binayak Kuikel
VIDEO: ट्रम्प नीतिले नेपालमा के असर पर्ला?? | Trump&#39;s TARIFF and it&#39;s effect in Nepal.
VIDEO: Surakshya Panta - Hridayendra Shah CONTROVERSY | WSO | Binayak Kuikel |
CHANNEL: UCTm_ZE0j6Nahzkdp8tR5oKg
VIDEO: Who Killed Nepali Football?
VIDEO: The Shreepech Heist
VIDEO: Why Harka Sampang Hates Balen
VIDEO: The Rise and Fall of GUNDARAJ
VIDEO: BALEN: The New MAHENDRA?
VIDEO: The Ride Sharing WAR of Nepal
VIDEO: अमेरिकी सेना नेपालमा? I The Dark Truth of SPP
VIDEO: TOP 3 BIGGEST BANK HEISTS IN NEPAL
VIDEO: The Real Power of Balen Shah &amp; His Ministers
VIDEO: PM BALEN’s 5-Year PLAN, Explained
VIDEO: Why the Middle East War Matters for Nepal
VIDEO: The Real Story of BALEN SHAH
VIDEO: NC vs RSP vs UML: Manifesto Explained
VIDEO: How Political Parties Make Money to Buy You
VIDEO: The Real Story of GAGAN THAPA
VIDEO: RSP will WIN this Election If They Fix This!
VIDEO: The REAL Story of Rabi Lamichhane
VIDEO: Top 10 Richest Politicians of Nepal
VIDEO: Nepal Airlines Boeing 757 Karnali
VIDEO: Most Expensive Mistake of Nepal Airlines
VIDEO: How Nepal Became a Haven for Money Laundering
VIDEO: Polymer Note Scam | Money &amp; Crime
VIDEO: What Went Wrong at Prabhu Bank?
VIDEO: How Nepal solved Japan’s Cash Crisis
VIDEO: The END of Prabhu Group?
VIDEO: How Lhasa NEWARS Became Rich
VIDEO: How A Poor Boy Built IME Empire
VIDEO: Why Made in Nepal Smartphones Failed?
VIDEO: The Dark Side of Notebandi | Demonetization Explained
VIDEO: Basnet vs Basnet: Nepal’s Biggest Airline War
VIDEO: The End of Nepal’s Economy?
VIDEO: Gen Z Protest: What Really Happened That Day?
VIDEO: म त कायर भएर बसिरहन सकिन। के तपाईँ बस्न सक्नुहुन्छ? #thaharesearch
VIDEO: माघ १९ र भदौ १९ || A Digital Coup? Social Media BAN @TheNepaliComment
VIDEO: KOSHI BARRAGE IN DANGER!
VIDEO: What is INTERPOL?
VIDEO: How India Tried to Steal Lipulekh from Nepal
VIDEO: The Rise of Bichauliya
VIDEO: Paytm inspired by Esewa? l Thaha Research #esewa
VIDEO: Jyoti vs Jyoti: Nepal’s Biggest Business War
VIDEO: Saurya Airlines 9N-AME Crash
VIDEO: Saurya Airlines को प्लेन के कारणले खस्यो? दोषी को? | Final Report | 3D Animation
VIDEO: Asgar Ali is More Powerful Than You Think
VIDEO: HOW NEPAL’S FIRST BILLIONAIRE VANISHED
VIDEO: RABI LAMICHHANE CASE ANALYSIS
VIDEO: Agni Sapkota and the Arjun Lama MURD*R case
VIDEO: King Mahendra: Great King or Dictator? (Full Story)
VIDEO: समय संगै फेरिएका बोलि || PM Kp Oli,King Prithvi Narayan Shah
VIDEO: King Gyanendra:The Good, The Bad &amp; The UGLY (Full Story)
VIDEO: THE RISE OF DR. SANDUK RUIT
CHANNEL: UC2-AXj9DqhAHEaOnfACTUDw
VIDEO: The Plan That Could Change Kathmandu Forever
VIDEO: The Picnic That Ended Rana Rule
VIDEO: How Nepal Lost Limpiyadhura...Forever | EON
VIDEO: अध्यादेश भनेको के हो? What is an ordinance?
VIDEO: This Oil Shock Is About To Hit Nepal | EON
VIDEO: How Kathmandu&#39;s Sukumbasi Settlement Changed Over Time?
VIDEO: This is how petrol and diesel are actually made.
VIDEO: How Getting Sick in Nepal Will Ruin You Financially?
VIDEO: Balen — The Most Powerful PM in Nepal&#39;s History? | EON
VIDEO: One Final Message Before The Election
VIDEO: Remembering Genz Martyrs | Ayush Thapa
VIDEO: Remembering Genz Martyrs | Nikita Gautam
VIDEO: Remembering Genz Martyrs | Sauran Kishor Shrestha
VIDEO: Remembering Genz Martyrs | Abhishek Chaulagain
VIDEO: Analyzing RSP&#39;s Chances Of Winning This Election | EON
VIDEO: Remembering Genz Martyrs | Rasik Khatiwada
VIDEO: Remembering Genz Martyrs | Buddhi Bahadur Tamang
VIDEO: Exposing Oli’s Lie On Facebook
VIDEO: Why The System Works For Them And Not For You?
VIDEO: Do We STILL Need Caste Based Reservation in Nepal?
VIDEO: Bhadra 24: Who were ACTUALLY responsible?
VIDEO: Why Do We LOVE Conspiracy Theories?
VIDEO: Register your name TODAY!
VIDEO: इतिहासले याद राख्नेछ!
VIDEO: How Oli Govt M*rdered 19 Children That Day? | EON
VIDEO: An Open Letter To Dear GenZs
VIDEO: Why Flyover Won’t Solve Koteshwor’s Traffic
VIDEO: The REAL Reason We Had 18 Hours Loadshedding
VIDEO: The Madhesh Problem: From Aandolan to Blockade
VIDEO: The Madhesh Problem: From Unification to Discrimination
VIDEO: Exposing a $216,000,000 Pokhara Airport Scam
VIDEO: Air India Crash - 3D Animation
VIDEO: How Terr*rists Use Nepal to Plan Major Attacks
VIDEO: The BIGGEST Storm Nepal Has Ever Seen
VIDEO: Kathmandu Is Choking – And It’s About to Get Worse
VIDEO: What ACTUALLY Happened In Tinkune?
VIDEO: Was Nepal BETTER Under King’s Rule?
VIDEO: The Rise and Fall of Nepal&#39;s First Planned City
VIDEO: Why are your vegetables expensive?
VIDEO: Could Kathmandu survive a fire like CALIFORNIA?
VIDEO: The Strange Problem With Goldstar Shoes
VIDEO: What If South Korean Plane Went Down on Kathmandu Runway?
VIDEO: How Government Is Destroying Your Future?
VIDEO: Is it TOO LATE to save Kathmandu now?
VIDEO: KP Oli Cambodia Kaanda in 1 minute #EON #echoesofnepal
VIDEO: Entire Life Of Donald Trump In 19 Minutes
VIDEO: How Girija Hijacked Royal Nepal Airlines?
VIDEO: How Girija HIJACKED Royal Nepal Airlines - Biratnagar Plane Hijack
VIDEO: The Last Ride Of Madan Bhandari
VIDEO: Israel vs Iran - Threat of World War 3?
CHANNEL: UCIUpvBA9ibPWHaDeH0G49Aw
VIDEO: Is Ronaldo still THE GOAT without the World Cup?
VIDEO: The Prince who could never become King :(
VIDEO: What it takes for Nepal to host the World Cup?
VIDEO: The real reason behind Cape Verde’s incredible run!
VIDEO: This Could be Nepal’s WORST DISASTER
VIDEO: The most CONTROVERSIAL goal in football history!                            #worldcup
VIDEO: We tested Kathmandu’s drinking water and found what companies don’t tell you
VIDEO: The Day Nepal Hosted the FIFA World Cup
VIDEO: Balen&#39;s Statement on Border: Right or Wrong?
VIDEO: The Problem with Balen&#39;s Politics
VIDEO: Inside Nepal’s Most Unusual Protest
VIDEO: Why do they keep talking nonsense?
VIDEO: Balen: Strong Leader or Dictator in Making? ft. Lee Kwan Yew
VIDEO: The TRAGIC Life of Bhairav Aryal
VIDEO: How Balen Took Over Nepali Politics
VIDEO: What if you were the PRIME MINISTER of Nepal?
VIDEO: US vs Iran War: Are Nepali workers at RISK ?
VIDEO: RSP vs UML vs NC vs NCP: Hawa Guff or Real Plan?
VIDEO: The Dark Reality of Winning Election in Nepal
VIDEO: Who will become next PM of Nepal? QUIZ
VIDEO: The Money Gap Nobody Talks About in Nepal
VIDEO: The Gurkha Who Fought Back: The True Story
VIDEO: The Hunt for India&#39;s Most Wanted Te*riorist in Nepal
VIDEO: Big Promises, Mixed Results: 100 Days of Sushila Karki
VIDEO: Inside Chitwan National Park | TNC Original Documentary
VIDEO: Is NPL might be world&#39;s most exciting cricket league?
VIDEO: Nicholous Bhusal: High IQ or Just High?
VIDEO: 3 Steps to make NPL as big as IPL
VIDEO: Can Nepal Build the Next IPL?
VIDEO: Why Nepali Can No Longer Afford a House
VIDEO: The BIPIN JOSHI STORY | Full Documentary
VIDEO: How KP Oli is Destroying UML (एमाले) ?
VIDEO: How Nepali films Changed over the years | The Nepali Comment
VIDEO: The Dark Reality of Kanda Videos in Nepal
VIDEO: How The Protest Was Truly GEN Z
VIDEO: Can Balen Win the Election?
VIDEO: Dear PM Sushila Karki
VIDEO: Who Burned Nepal? Gen Z or Hidden Forces?
VIDEO: GEN Z Protest in Nepal: What exactly Happened?
VIDEO: Nepal Government is banning EVERYTHING !
VIDEO: Gyanendra Shahi: The Man, the Myth, the Legend
VIDEO: The INSANE Rise of EV in Nepal
VIDEO: 436 manxe khane bagh ko sikaar!
VIDEO: Kasari maariyo ta 436 manxe khaane bagh?
VIDEO: The Man, the Myth, the Legend: Harka Sampang
VIDEO: King Mahendra vs BP Koirala: Nepal&#39;s BIGGEST Rivalry
VIDEO: The deadliest MAN-EATER in history!
VIDEO: What if Nepal is CAPTURED overnight?
VIDEO: Why South Korea&#39;s President&#39;s Rule was overthrown?
VIDEO: Why is &#39;Brindaban ko Sikari&#39; problematic?

,channel,video,video_id,comment,published_at
0,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,"Thank you,plz support country. Not person who ...",2026-07-21T05:24:45Z
1,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,Thank you uncle for your insights. \nMy indepe...,2026-07-20T15:51:06Z
2,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,open your eyes and mind don't be manipulated b...,2026-07-20T14:01:02Z
3,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,Nagar prahari lai training dinu parcha they al...,2026-07-20T04:48:59Z
4,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,How does one man surpass the nation's media? \...,2026-07-20T02:09:24Z

In [17]:
yt_comments["comment"] = yt_comments["comment"].apply(clean_text)

print(f"Total Length of data = {yt_comments.shape}")

yt_comments.head()

Total Length of data = (8843, 5)

,channel,video,video_id,comment,published_at
0,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,thank youplz support country not person who wa...,2026-07-21T05:24:45Z
1,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,thank you uncle for your insights my independe...,2026-07-20T15:51:06Z
2,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,open your eyes and mind dont be manipulated by...,2026-07-20T14:01:02Z
3,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,nagar prahari lai training dinu parcha they al...,2026-07-20T04:48:59Z
4,UCJUFkLE5GjqloVigynCN4VA,The Truth : चमे*ली ग्यां*ग - भ्रम र वास्तविकता...,Cyi4xfHYswQ,how does one man surpass the nations media by ...,2026-07-20T02:09:24Z

In [18]:
yt_comments.to_csv("./datasets/yt_comments.csv", index=False)